version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Use the custom Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app:cached  # Cache the host folder to improve performance
      - node_modules:/app/node_modules  # Use a named volume for node_modules
    working_dir: /app
    command: ["npm", "run", "serve"]
    env_file:
      - .env
    network_mode: "host"  # Use the host's network stack

volumes:
  node_modules:
